```
output: pdf_document
```

```{r}
library(dplyr)
library(ggcorrplot)
library(readr)
library(FactoMineR)
library(factoextra)
```

```{r}
# Load data
data <- read_csv("../data/mxmh_survey_results.csv", show_col_types = FALSE)
# Remove Frequency [] where necessary
columns <- colnames(data)
frequency_columns <- columns[grep("^Frequency", columns)]
remove_frequency_prefix <- function(col_name) {
  col_name <- sub("^Frequency \\[", "", col_name)
  sub("]$", "", col_name)
}
#print(frequency_columns)
colnames(data) <- sapply(columns, remove_frequency_prefix)
frequency_columns <- sapply(frequency_columns, remove_frequency_prefix)
columns <- colnames(data)
# Save raw_data
raw_data = data
# Convert the ordinal values to numbers
map_function <- function(x) {
  case_when(
    x == "Never" ~ 0,
    x == "Rarely"~ 1,
    x == "Sometimes"~ 2,
    x == "Very frequently"~ 3,
    TRUE ~ NA_integer_  # If none of the conditions are met, return NA
  )
}
for (col in frequency_columns) {
  data = mutate(data, {{col}} := map_function(data[col]))
}
print(data)
```

```{r fig.align = "center", fig.width = 14, fig.height = 14}
a <- data[frequency_columns]
ggcorrplot(as.data.frame(cor(as.matrix(a))),  type = "lower", lab = TRUE)
```

```{r fig.align = "center"}
mca <- MCA(raw_data[frequency_columns], graph = FALSE)
plot(fviz_mca_var(mca, choice = "mca.cor", repel = TRUE,
                  ggtheme = theme_minimal()))
```
